pipeline:
  identifier: Build_amolathavale_jspring_1744578399980
  name: Build jspring
  orgIdentifier: myWiproLearning
  projectIdentifier: AAAHarness_Project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: amolathavale/jspring
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Maven_Build
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:eclipse-temurin-21-alpine
                    shell: Sh
                    command: |-
                      mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
                      mvn test -B
                contextType: Pipeline
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: amolathavale/jspring
                    tags:
                      - "1.2"
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Abort
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
